BoltzExchange/boltz-backend

package-lock.json, package.json
I needed to publish `v0.0.2` to [NPM](https://www.npmjs.com/package/boltz-backend) after merging #22 because the `detectSwap` method is required for https://github.com/BoltzExchange/boltz-frontend/pull/10. 
I will tag a release on GitHub after this PR is merged.
=> chore: bump version to 0.0.2

lib/chain/ChainClient.ts, lib/chain/ChainClientInterface.ts, lib/lightning/Errors.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, lib/wallet/Wallet.ts, package.json
This PR:
- fixes some minor details (wording, code style, and cleanup of the test scripts in `package.json`)
- removes the `estimateFee` RPC call from the ChainClient because LTCD does not support it. Checkout [this commit message](https://github.com/BoltzExchange/boltz-backend/commit/358dc252ad10b92663be13f2540e9257ee9d9981) for a more comprehensive explanation why.
=> Style & fee estimation

lib/Config.ts, lib/Utils.ts, lib/chain/ChainClient.ts, lib/chain/ChainClientInterface.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, lib/wallet/UtxoRepository.ts, lib/wallet/Wallet.ts, package-lock.json, test/integration/chain/ChainClient.spec.ts, tsconfig.json, tslint.json
This PR is the first one that starts working on improving the wallet of `boltz-backend`. Unconfirmed funds that Boltz found in the mempool before a restart will be looked up to find out whether they got included in a block and if not treated like all other unconfirmed UTXOs (listen to events from BTCD until included in a block).
From this PR onwards the BTCD and LTCD nodes Boltz is connected to have to have `txindex` enabled so that the aforementioned transactions can be looked up.
=> Check unconfirmed UTXOs on startup

lib/consts/Database.ts, lib/db/Database.ts, lib/db/models/Ouput.ts, lib/db/models/Utxo.ts, lib/swap/SwapManager.ts, lib/wallet/OutputRepository.ts, lib/wallet/UtxoRepository.ts, lib/wallet/Wallet.ts, lib/wallet/WalletManager.ts, test/integration/wallet/Wallet.spec.ts, test/unit/wallet/Wallet.spec.ts, test/unit/wallet/WalletManager.spec.ts
This PR refactors the way UTXOs and addresses are handled by separating the UTXOs and outputs (scripts of the addresses) in the database which means that:
- every address can have multiple UTXOs in an efficient way (also known as address reuse; should be avoided if possible)
- there are no problems if a single transaction sends funds to multiple addresses of Boltz (the transaction hash used to be the primary key of the `utxos` table in the database)
- Boltz listens new transactions on all addresses the wallet ever created. Before this PR Boltz forgot about old addresses it created  on every restart.
This is a breaking change to the database. Please remove your existing `boltz.db` before running Boltz.
=> feat: detect multiple UTXOs per output

lib/grpc/GrpcService.ts, lib/lightning/LndClient.ts, lib/proto/boltzrpc_pb.d.ts, lib/proto/boltzrpc_pb.js, lib/service/Service.ts, proto/boltzrpc.proto
This PR adds the `preimage` to the invoice settled events so that the user doesn't have to paste it manually.
=> feat(grpc): add preimage to invoice settled events

docker/berkeley-db/Dockerfile, docker/bitcoin-core/Dockerfile, docker/build-images.sh, docker/litecoin-core/Dockerfile
This PR moves the build of Berkeley DB from the images of Bitcoin Core and Litecoin Core into its own Dockerfile which should reduce the build time of the images.
=> chore: move Berkeley DB build into own container

docker/regtest/Dockerfile, lib/chain/ZmqClient.ts, lib/wallet/Wallet.ts, package-lock.json, package.json
`pubrawblock` sometimes stops working on Litecoin Core for whatever reason. It is not related to our Docker image because it also happens on https://testnet.boltz.exchange too which is running a normal binary of Litecoin Core. To fix that I added a fallback for that ZMQ filter: `pubhashblock`. The fallback is way slower than `pubrawblock` because it depends on sending a RPC request to Litecoin Core to get the data about the block but it is still much better than not getting informed about new blocks at all.
For handling the events from `pubhashblock` I needed a lock because if an event handler is `async`, Node doesn't wait until it is done before sending the next event. And while I was already at it, I also added such a lock to the wallet to prevent race conditions and double spending …
=> Fallback for pubrawblock and lock for wallet

lib/swap/SwapManager.ts
This PR fixes an bug that caused the block height of the wrong chain to be queried
=> fix: correct timeout block height in map

bin/boltzd, lib/Config.ts, package.json
This PR removes code that got deprecated with the switch to Bitcoin Core and fixes the parsing of config files that are not located in the default path.
Maybe we should add parsing of the config files of Bitcoin / Litecoin Core and LND in the future again but I don't think that it is important right now.
=> fix: config file parsing

lib/db/models/Wallet.ts, lib/lightning/LndClient.ts, lib/swap/SwapNursery.ts
This PR should cause that LND errors, which are thrown when trying to pay invoices, are handled gracefully.
=> fix: catch LND errors when paying invoices

lib/Utils.ts, lib/swap/SwapManager.ts
This PR in combination with a fix in the frontend should make the fee calculation of reverse swaps of the `LTC/BTC` pair more accurate.
=> fix: fee calculation of reverse swaps

docker/lnd/Dockerfile
This PR just bumps the Go version of the Docker LND image.
Btw: I updated the [Litecoin regtest LND branch](https://github.com/BoltzExchange/lnd/pull/1) so that it is on par with the latest LND release again.
=> chore: update Go alpine version

lib/cli/BuilderComponents.ts, lib/cli/commands/SendCoins.ts, lib/db/models/Output.ts, lib/db/models/Utxo.ts, lib/db/models/Wallet.ts, lib/proto/boltzrpc_pb.d.ts, lib/proto/boltzrpc_pb.js, lib/service/Service.ts, lib/wallet/Wallet.ts, proto/boltzrpc.proto, test/integration/wallet/Wallet.spec.ts
This PR adds the option to spend all funds of the wallet in one transaction. That feature is nice to have for database migrations in which the funds have to be sent to a temporary wallet.
=> feat: send all funds of wallet

lib/chain/ChainClient.ts, lib/chain/ZmqClient.ts, test/unit/chain/ZmqClient.spec.ts, tslint.json
Closes https://github.com/BoltzExchange/boltz-backend/issues/96
This PR adds a feature that allows Boltz to detect reorganizations of the BTC and LTC chains. It does not mark UTXOs as unconfirmed after a reorganization or any other advanced things but just make sure no block height is missed by the `block` events of the `ZmqClient`
=> feat: detection of chain reorganizations

docker/berkeley-db/Dockerfile, docker/bitcoin-core/Dockerfile, docker/litecoin-core/Dockerfile, docker/lnd/Dockerfile, docker/regtest/Dockerfile, docker/regtest/data/core/config.conf, docker/regtest/scripts/setup.sh, docker/regtest/scripts/utils.sh
This PR updates the alpine base images of our Docker images to `3.9.3` and:
- updates Bitcoin Core to version `0.18.0`. The RPC call `generate` was deprecated in that version but it can still be used until `0.19.0` (I had to manually allow that call [in the config](https://github.com/BoltzExchange/boltz-backend/compare/update-bitcoin-core?expand=1#diff-9b9353917242ad1d1b179693e2624521R13)). [Here](https://bitcoincore.org/en/releases/0.18.0/) is the complete changelog for reference.
- updates Litecoin Core to `0.17.1`. Mining a new block with `generate` still fails on Litecoin occasionally. I tried changing the base images to [`debian-slim`](https://hub.docker.com/_/debian) but it didn't have any influence on that issue. There is a PR that fixes this bug already but it will probably take a …
=> chore: update Docker images

package-lock.json
All of the vulnerable dependencies were not used by Boltz itself but as dependencies of dev-dependencies (only needed for the development environment). This PR updates them anyways.
=> chore: update vulnerable dependencies

.travis.yml, test/Utils.ts
This PR add a Travis build file to the repo without removing the one for CircleCI. I want to keep running both in parallel for a while and test which one suits our needs best and is less flaky.
Btw: [this little change](https://github.com/BoltzExchange/boltz-backend/compare/travis?expand=1#diff-1f18275d9b4d7c24cfb053ee06434a25R17) made the CircleCI build a lot more stable and reliable. Maybe it solves our problem with the flaky integration tests entirely.
=> chore: switch from CircleCI to Travis

lib/Utils.ts, lib/service/Service.ts, package-lock.json, package.json, test/unit/Utils.spec.ts
I updated [our fork of of the lightning invoice parsing library](https://github.com/boltzexchange/bolt11) to fix the issues we had with parsing invoices on testnet. Which means that we can use the library again.
=> fix: invoice decoding library

lib/chain/ChainClient.ts, lib/chain/ZmqClient.ts, lib/proto/boltzrpc_grpc_pb.js, lib/proto/boltzrpc_pb.d.ts, lib/proto/boltzrpc_pb.js, lib/service/Service.ts, proto/boltzrpc.proto, test/unit/service/Service.spec.ts
I have observed some weird behavior with Submarine Swaps: when the 0-conf transaction is rejected and the daemon is waiting for the it to be included in a block, it never detects the transaction to be confirmed even if it is mined.
To debug this I added the highest scanned block of the `ZmqClient` (the class handling new blocks and transactions from Bitcoin/Litecoin Core) to the response of the `GetInfo` gRPC call.
=> fix: add scanned block height to GetInfo

docs/api.md, docs/deployment.md, docs/lifecycle.md, lib/api/Controller.ts, lib/lightning/LndClient.ts, lib/service/EventHandler.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts
This PR changes the behavior of the prepay miner fee Reverse Swap protocol so that both invoices (the miner fee one and the actual hold invoice) are revealed in the response of the `/createswap` call.
=> refactor: reveal both invoices in prepay minerfee protocol

docs/lifecycle.md, lib/api/Controller.ts, lib/consts/Enums.ts, lib/service/EventHandler.ts, lib/swap/ChannelNursery.ts, lib/swap/SwapNursery.ts, test/unit/api/Controller.spec.ts, test/unit/service/EventHandler.spec.ts, test/unit/service/Service.spec.ts, test/unit/swap/ChannelNursery.spec.ts
This PR adds a new swap update event (`channel.created`) that notifies the clients about opened channels:
```json
{
"status": "channel.created",
"channel": {
"fundingTransactionId": "80a3718319b576b0422ab407a5766df052a89eccf9789d90e0d250e3fc2734f7",
"fundingTransactionVout": 0
}
}
```
=> feat: add "channel.created" event

lib/db/Database.ts, lib/db/DatabaseVersionRepository.ts, lib/db/Migration.ts, lib/db/ReverseSwapRepository.ts, lib/db/models/DatabaseVersion.ts, lib/db/models/KeyProvider.ts, test/unit/db/Migration.spec.ts
To allow graceful database migrations in the future, this PR introduces a new database table that stores nothing but an integer which defines the database schema version. Based on that schema version, future breaking database changes can be handled gracefully by detecting the schema of the existing database and updating it accordingly.
=> feat: add database version schema

.github/workflows/ci.yml, jest.config.js, run-int.js
Just running `npm run test:int` became flaky
=> fix: custom integration test runner for CI

lib/db/models/ReverseSwap.ts, lib/db/models/Swap.ts, lib/notifications/CommandHandler.ts, lib/notifications/DiscordClient.ts, lib/notifications/Markup.ts, lib/notifications/NotificationProvider.ts, test/unit/notifications/CommandHandler.spec.ts
Allows querying swaps by:
- id
- invoice
- preimage hash
- lockup address
- lockup transaction
=> feat: query swapinfo by more columns

docs/api.md
- Made ### headings unique so they can be uniquely linked
- Moved "RSK Testnet Only" disclaimer out of heading
- `rBTC` -> `RBTC`
=> docs: rsk fixes

lib/Boltz.ts, lib/Config.ts, lib/Core.ts, lib/PromiseUtils.ts, lib/Utils.ts, lib/api/Utils.ts, lib/chain/ChainClient.ts, lib/chain/ElementsClient.ts, lib/chain/ElementsWrapper.ts, lib/chain/ZmqClient.ts, lib/service/ElementsService.ts, lib/service/cooperative/DeferredClaimer.ts, lib/swap/SwapNursery.ts, lib/swap/UtxoNursery.ts, lib/wallet/WalletManager.ts, lib/wallet/providers/CoreWalletProvider.ts, lib/wallet/providers/ElementsWalletProvider.ts, lib/wallet/providers/LndWalletProvider.ts, test/integration/Core.spec.ts, test/integration/Nodes.ts, test/integration/chain/ElementsWrapper.spec.ts, test/integration/service/TimeoutDeltaProvider.spec.ts, test/integration/service/cooperative/DeferredClaimer.spec.ts, test/integration/service/cooperative/MusigSigner.spec.ts, test/integration/wallet/ethereum/ContractEventHandler.spec.ts, test/unit/PromiseUtils.spec.ts, test/unit/api/Utils.spec.ts
This PR refactors the codebase use `IChainClient` for interacting with UTXO based chains. Based on that `ElementsWrapper` is implemented which handles two `ElementsClient`s. One is publicly reachable, the other one lowball.
Right now we use lowball only for checking unconfirmed transactions. RPC calls of `ElementsWrapper` are adjusted to handle two clients (eg when getting a raw transaction, call both clients and use the one that has the info).
Some minor type fixes of tests are also in this PR.
=> feat: use lowball for emitting unconfirmed transactions

lib/Boltz.ts, lib/Prometheus.ts, lib/PromiseUtils.ts, lib/api/Api.ts, lib/api/Controller.ts, lib/api/SwapInfos.ts, lib/api/v2/WebSocketHandler.ts, lib/api/v2/routers/SwapRouter.ts, test/integration/chain/ElementsWrapper.spec.ts, test/integration/rates/LockupTransactionTracker.spec.ts, test/unit/BaseClient.spec.ts, test/unit/PromiseUtils.spec.ts, test/unit/api/Controller.spec.ts, test/unit/api/SwapInfos.spec.ts, test/unit/api/Utils.spec.ts, test/unit/api/v2/routers/SwapRouter.spec.ts, test/unit/notifications/BalanceChecker.spec.ts, test/unit/notifications/CommandHandler.spec.ts, test/unit/notifications/DiskUsageChecker.spec.ts, test/unit/swap/EthereumNursery.spec.ts, test/unit/swap/LightningNursery.spec.ts, test/unit/swap/NodeFallback.spec.ts, test/unit/swap/PaymentHandler.spec.ts, test/unit/swap/UtxoNursery.spec.ts
Fetching the status of all swaps on startup takes a couple seconds and is not necessary. Almost all swaps in the database are already done and their status will never be fetched again.
Therefore, we only fetch the swap status as needed and cache after fetching.
=> refactor: swap status cache

LICENSE, README.md
This PR reverts https://github.com/BoltzExchange/boltz-backend/pull/323 returning to AGPLv3. Credit to @kingonly who convinced us of doing this.
As a contributor, please reply with "ACK" as comment below to confirm your consent for the license change! @michael1011 @dni @tiero @peartobear @ImmanuelSegol @yuyaogawa
This PR represents my ACK.
=> chore: change license to AGPL-3

docker/boltz/Dockerfile
Saves 80MB in the final image by not including NPM dev dependencies.
=> chore: optimize backend Dockerfile

lib/api/v2/routers/SwapRouter.ts, swagger-spec.json
It is not required because when a swap is already settled from our perspective, we do not require the preimage to be sent to create a partial signature.
=> fix: make preimage optional in chain swap claim endpoint

lib/api/v2/routers/SwapRouter.ts, lib/service/cooperative/EipSigner.ts, swagger-spec.json
When a client scans the contract event logs to find refundable swaps, it does not know the swap id. We need to use a different identifier in that scenario, and the only other option is the preimage hash.
=> feat: sign cooperative EVM refund by preimage hash

lib/api/v2/routers/SwapRouter.ts, lib/cli/ethereum/EthereumUtils.ts, lib/service/InvoiceExpiryHelper.ts, lib/service/Service.ts, lib/swap/Errors.ts, lib/swap/SwapManager.ts, swagger-spec.json, test/unit/api/v2/routers/SwapRouter.spec.ts, test/unit/service/InvoiceExpiryHelper.spec.ts, test/unit/swap/SwapManager.spec.ts
=> feat: custom invoice expiry for reverse swaps

docker/build.py, docker/regtest/Dockerfile, docker/regtest/data/core/config.conf, docker/regtest/startRegtest.sh, lib/VersionCheck.ts, swagger-spec.json
LND does not support Bitcoin Core v28.0 yet: https://github.com/lightningnetwork/lnd/pull/9154
=> chore: bump Bitcoin Core to v28.0

boltzr/Cargo.lock, boltzr/Cargo.toml, boltzr/build.rs, boltzr/src/evm/refund_signer.rs, boltzr/src/grpc/status_fetcher.rs, boltzr/src/metrics/server.rs
When we get subscriptions to the SSE or WebSocket before the backend connects to the sidecar, the latest state of the swap would not be sent to the client. To fix that, requests for swap status updates are buffered in the sidecar until the backend connects
=> Buffer swap status updates before backend connects

lib/Utils.ts, lib/service/cooperative/DeferredClaimer.ts, test/unit/Utils.spec.ts
Creating batch claim transactions with more than ~20 inputs on Liquid does not work with Node.js. To work around that, we create multiple batch sweeps with at most 15 inputs each.
=> fix: chunk batch claim transactions

docs/libraries.md
Gitbook can't handle embedded links in hints or broke it recently 😠
=> docs: fix library section hint link

lib/db/Database.ts, lib/db/repositories/TransactionLabelRepository.ts, test/integration/db/repositories/TransactionLabelRepository.spec.ts
Hpapens quite a bit when restarting the regtest containers
=> refactor: handle duplicate transaction labels

lib/api/v2/routers/SwapRouter.ts, lib/service/cooperative/MusigSigner.ts, swagger-spec.json, test/integration/service/cooperative/MusigSigner.spec.ts, test/unit/api/v2/routers/SwapRouter.spec.ts
Closes #744
I really don't want another endpoint for this. Making the existing one work without a transaction seems reasonable. Wdyt @jackstar12?
=> feat: make transaction optional in reverse claim endpoint

lib/db/models/Referral.ts, lib/lightning/LightningClient.ts, lib/lightning/LndClient.ts, lib/lightning/cln/ClnClient.ts, lib/rates/providers/RateProviderTaproot.ts, test/integration/db/models/Referral.spec.ts, test/unit/rates/providers/RateProviderTaproot.spec.ts
Needed for https://github.com/BoltzExchange/boltz-web-app/issues/784
=> feat: include max routing fee in submarine pairs when queried with ref

.github/workflows/ci.yml, boltzr/Cargo.toml
When the build is stripped, the profiler does not work
=> chore: do not strip sidecar release build

lib/swap/NodeSwitch.ts, test/unit/service/Service.spec.ts, test/unit/swap/NodeSwitch.spec.ts
Workaround until https://github.com/ElementsProject/lightning/issues/8042 is fixed
Might be useful in the future for other scenarios too
=> feat: select node to pay invoices based on routing hints

lib/service/Service.ts
Closes #810
When Bitcoin blocks come in faster or slower than expected, the 25% buffer for timeout block heights of chain swaps could not be enough. This commit bumps that buffer to 50%. The UX will not suffer from it because cooperative refunds are possible when the timelock did not expire yet.
=> chore: bump chain swap timeout buffer to 50%

lib/api/Errors.ts, lib/api/v2/routers/ReferralRouter.ts, lib/api/v2/routers/SwapRouter.ts, lib/db/Database.ts, lib/db/models/ExtraFee.ts, lib/db/repositories/ExtraFeeRepository.ts, lib/rates/FeeProvider.ts, lib/service/Renegotiator.ts, lib/service/Service.ts, test/integration/db/repositories/ExtraFeeRepository.spec.ts, test/integration/service/Renegotiator.spec.ts, test/unit/api/v2/routers/ReferralRouter.spec.ts, test/unit/api/v2/routers/SwapRouter.spec.ts, test/unit/rates/FeeProvider.spec.ts, test/unit/service/Service.spec.ts
Allow clients to add extra fees to swaps by passing these parameters when creating swaps:
```json
{
...
"extraFees": {
"id": "gm",
"percentage": 1
}
}
```
Those extra fees added can be queried with API keys via `/v2/referral/stats/extra`:
```json
{
"2025": {
"2": {
"gm": 13000
}
}
}
```
Do we want to allow this for every referral?
=> feat: nested extra fees

lib/db/repositories/ReverseRoutingHintRepository.ts, lib/notifications/CommandHandler.ts, test/unit/notifications/CommandHandler.spec.ts
When calling "swapinfo" with an EVM address, it will query all swaps that have coins locked that can be claimed by that address.
=> feat: add EVM address to swapinfo command

lib/chain/ElementsWrapper.ts, lib/chain/elements/TestMempoolAccept.ts, lib/chain/elements/ZeroConfCheck.ts, lib/chain/elements/ZeroConfTool.ts, test/integration/chain/ElementsWrapper.spec.ts, test/integration/chain/elements/TestMempoolAccept.spec.ts
Not needed on regtest and was causing unnecessary delays in E2E tests
=> fix: skip mempool acceptance check on regtest

boltzr/src/api/ws/status.rs, docs/api-v2.md
In the browser (e.g. WASM clients), it isn't possible to manage WebSocket ping/pong frames directly. 
This PR introduces app-level ping/pong messages to the WebSocket status stream so that clients can implement a consistent keep-alive mechanism that works across native and WASM builds.
=> Add websocket app-level ping/pong support

.gitignore, lib/Config.ts, lib/lightning/Errors.ts, lib/lightning/PendingPaymentTracker.ts, lib/swap/LightningNursery.ts, lib/swap/PaymentHandler.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts, test/integration/lightning/PendingPaymentTracker.spec.ts, test/unit/lightning/PendingPaymentTracker.spec.ts, test/unit/swap/PaymentHandler.spec.ts
Closes #609
Adds a global invoice timeout after which backend won't attempt new payments and considers the payment as permanently failed.
=> feat: invoice timeout

boltzr/src/api/errors.rs, boltzr/src/api/mod.rs
```
2025-03-30T14:19:17.492906Z  WARN boltzr::api::errors: src/api/errors.rs:107: Request to /v2/lightning/BTC/node/asdf failed with 400 Bad Request: {"error":"invalid node: invalid character 's' at position 1"} status=400
```
=> feat: log failed HTTP requests in sidecar

lib/db/Migration.ts, lib/db/models/Swap.ts
Some BOLT12 invoices could be too long for being indexed by a B-Tree, so we have to drop the explicit index and the unique constraint.
The error:
index row size x exceeds btree version 4 maximum 2704 for index
=> fix: drop B-Tree indexes on invoices column of swaps

lib/cli/ethereum/EthereumUtils.ts
Ensures proper path resolution on MacOS when loading the wallet seed.
=> fix: use consistent data directory paths in EthereumUtils

.github/workflows/ci.yml
Was causing issues because clippy from Rust Nightly wants changes that are unstable in the Rust Stable version
=> chore: remove Rust Nightly from CI

lib/proto/boltzrpc_pb.d.ts, lib/proto/boltzrpc_pb.js, lib/swap/SwapManager.ts, lib/swap/hooks/CreationHook.ts, proto/boltzrpc.proto, test/unit/swap/SwapManager.spec.ts, test/unit/swap/hooks/CreationHook.spec.ts
This added param returned in the `SwapCreation` hook can allow you to reject swaps based on properties encoded in the returned invoice, including node pubkey - in the case of BOLT 11 submarine swaps.
=> feat: Add invoice to submarine swap creation hook

docker/build.py, docker/docker-scripts.sh, docker/regtest/startRegtest.sh
I couldn't fetch the regtest docker image on 4.8.4 due to not being available for arm64 (for Apple Silicon). I also noticed a spot in docker-scripts.sh that still used cookie authentication despite it being removed in #943
=> Docker regtest fixes

boltzr/src/lightning/cln/hold.rs, boltzr/src/lightning/cln/invoice_fetcher.rs, boltzr/src/lightning/cln/mod.rs, boltzr/src/webhook/invoice_caller.rs
Some mobile clients don't close the Websocket cleanly before exiting. That can result in us trying to talk to them via the Websocket and them never responding. Therefore, we have a shorter timeout on the Websocket BOLT12 invoice requests now and fallback to the Webhook in case the client does not respond on the Websocket in time.
=> feat: fallback to Webhook BOLT12 invoice fetching after Websocket timeout
