lib/cli/Utils.ts, lib/cli/commands/ClaimSwap.ts, lib/cli/commands/RefundSwap.ts, lib/cli/inquire.ts, package-lock.json, package.json
=> feat: add inquirer as optional input for boltz-cli

docker/btcd/Dockerfile, docker/lnd/Dockerfile, docker/ltcd/Dockerfile
I also pushed the latest versions of all images to Docker Hub
=> chore: update Go versions in Docker images

lib/wallet/Wallet.ts
=> refactor: Custom fee for sendToAddress method of Wallet closes #54

lib/cli/BuilderComponents.ts, lib/cli/commands/ClaimSwap.ts, lib/cli/commands/CreateReverseSwap.ts, lib/cli/commands/CreateSwap.ts, lib/cli/commands/RefundSwap.ts, lib/grpc/GrpcService.ts, lib/proto/boltzrpc_pb.d.ts, lib/proto/boltzrpc_pb.js, lib/service/Service.ts, lib/swap/SwapManager.ts, proto/boltzrpc.proto
This PR does a little cleanup https://github.com/BoltzExchange/boltz-backend/pull/57 to make the naming more consistent and fix a few little details that were overlooked
=> chore: cleanup of timeout naming scheme

lib/chain/ChainClient.ts, lib/chain/ChainClientInterface.ts, lib/cli/BuilderComponents.ts, lib/lightning/LndClient.ts, lib/service/Service.ts, lib/swap/Errors.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts, lib/wallet/Wallet.ts
=> feat: automatically refund failed swaps

lib/swap/SwapManager.ts
I did an oopsie and forgot to remove two logs statements before opening #73
=> chore: remove unnecessary log statement

lib/db/Database.ts, lib/db/models/Ouput.ts, lib/db/models/Utxo.ts
This is just a minor fix that **doesn't break anything** and will take effect when a new database is created.
=> fix: outputs to wallet table relation

lib/Boltz.ts, lib/proto/boltzrpc_pb.d.ts, lib/proto/boltzrpc_pb.js, lib/service/Service.ts, lib/swap/SwapManager.ts, lib/wallet/Wallet.ts, proto/boltzrpc.proto
This PR adds an additional field to the gRPC messages that start a swap (`CreateSwapRequest` and `CreateReverseSwapRequest`) that sets the trading fee.
=> feat: add additional field for fee of swap

lib/chain/ChainClient.ts, lib/chain/Errors.ts, lib/chain/ZmqClient.ts, lib/consts/Types.ts, lib/db/models/Utxo.ts, lib/wallet/Wallet.ts, package-lock.json, package.json, test/Utils.ts, test/integration/chain/ChainClient.spec.ts, test/integration/swap/Swap.spec.ts, test/integration/wallet/Wallet.spec.ts, test/unit/chain/ChainClient.spec.ts, test/unit/chain/ZmqClient.spec.ts, test/unit/wallet/WalletManager.spec.ts
Preparation for #96 
This PR adds a few unit tests for the chain and ZMQ clients.
=> test: unit tests for chain and zmq clients

lib/lightning/LightningClient.ts, lib/lightning/LndClient.ts, lib/proto/lndrpc_grpc_pb.d.ts, lib/proto/lndrpc_grpc_pb.js, lib/proto/lndrpc_pb.d.ts, lib/proto/lndrpc_pb.js, lib/swap/Errors.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts, proto/lndrpc.proto
This PR:
- updates the LND protobuf to version 0.6-beta
- checks whether a payment can be routed before creating a swap
=> Invoice route check

lib/swap/SwapManager.ts
If there are route hints the routability check could fail although the LND could pay the invoice
=> fix: could not find route for private channels

lib/swap/SwapManager.ts
Fixes the `if` statement introduces in https://github.com/BoltzExchange/boltz-backend/pull/112
=> fix: route hint list length check

lib/notifications/NotificationProvider.ts, test/unit/notifications/NotificationProvider.spec.ts
Was requested by @armurbalda:
`Can we do the line break after the last line please and the remove line break after the [mainnet] line?`
=> refactor: reformat swap messages

lib/notifications/DiscordClient.ts, lib/notifications/DiskUsageChecker.ts, lib/notifications/NotificationProvider.ts, package-lock.json, package.json, test/unit/notifications/DiskUsageChecker.spec.ts
Closes #130
I set the warning threshold to 90% for now
=> feat: add notification when disk is getting full

docs/index.md
Closes: https://github.com/BoltzExchange/boltz-frontend/issues/212
=> docs: add missing discord link

lib/api/Controller.ts, test/unit/api/Controller.spec.ts
Closes #156 
Based on feedback from this tweet: https://twitter.com/citlayik/status/1175489970510782464
=> feat: accept invoices with upper case letters

lib/Utils.ts, lib/notifications/NotificationProvider.ts, lib/swap/SwapManager.ts, package-lock.json, package.json, test/unit/Utils.spec.ts, test/unit/notifications/NotificationProvider.spec.ts
=> Readable Discord notifications

lib/Utils.ts
> 1/14/2021, 24:18:34
It was behaving weird on servers that are not on UTC :upside_down_face:
=> fix: timestamp of log messages

docker/docker-scripts.sh
add docker-scripts.sh from https://docs.boltz.exchange/en/latest/regtest/
=> add docker aliases script

LICENSE, README.md
As a contributor, please reply with `ACK` as comment below to confirm your consent for the license change. @michael1011, @dni, @tiero, @peartobear, @ImmanuelSegol, @yuyaogawa
=> license: change to BSL 1.1

lib/db/Database.ts, lib/lightning/LndClient.ts, lib/swap/PaymentHandler.ts, test/integration/Nodes.ts, test/integration/lightning/LndClient.spec.ts
=> fix: Lightning payment reliability

README.md
Add LICENSE partnership hint to README (same wording as https://github.com/BoltzExchange/boltz-web-app/pull/254) smaller fixes.
=> chore: README Update

lib/Boltz.ts, lib/Config.ts, lib/notifications/BalanceChecker.ts, lib/notifications/DiscordClient.ts, lib/notifications/NotificationProvider.ts, test/unit/notifications/BalanceChecker.spec.ts, test/unit/notifications/DiscordClient.spec.ts
- notifications for the Liquid wallet
- optional, separate channel for alerts
=> feat: separate notification channel for alerts

docs/deployment.md, lib/data/Stats.ts, lib/db/repositories/StatsRepository.ts, lib/notifications/CommandHandler.ts, test/unit/notifications/CommandHandler.spec.ts
- shows totals and grouped by pair
- only includes swaps in which money was sent in failure rates
- only current and last 6 months by default
=> refactor: getstats command

docs/deployment.md, lib/Boltz.ts, lib/Config.ts, lib/consts/Types.ts, lib/lightning/LightningClient.ts, lib/service/InvoiceExpiryHelper.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, test/integration/lightning/ClnClient.spec.ts, test/integration/lightning/LndClient.spec.ts, test/unit/service/InvoiceExpiryHelper.spec.ts, test/unit/swap/SwapManager.spec.ts
=> Reverse Swap invoice expiry

lib/api/Bouncer.ts, lib/api/Controller.ts, lib/api/Utils.ts, lib/api/v2/ApiV2.ts, lib/api/v2/routers/ReferralRouter.ts, lib/api/v2/routers/RouterBase.ts, lib/cli/commands/QueryReferrals.ts, lib/data/ReferralStats.ts, lib/data/Stats.ts, lib/db/repositories/StatsRepository.ts, lib/notifications/CommandHandler.ts, swagger-spec.json, test/integration/wallet/providers/ElementsWalletProvider.spec.ts, test/unit/api/Bouncer.spec.ts, test/unit/api/Controller.spec.ts, test/unit/api/v2/ApiV2.spec.ts, test/unit/api/v2/routers/ReferralRouter.spec.ts, test/unit/api/v2/routers/RouterBase.spec.ts, test/unit/notifications/CommandHandler.spec.ts
=> feat: referral API v2

docs/deployment.md, package-lock.json, package.json
=> Postgres docs

lib/api/v2/routers/ChainRouter.ts, lib/notifications/clients/MattermostClient.ts, lib/service/Service.ts, swagger-spec.json, test/unit/api/v2/routers/ChainRouter.spec.ts, test/unit/service/Service.spec.ts
=> Block height API

tools/plugins/mpay/mpay.py, tools/plugins/mpay/pay/invoice_check.py, tools/plugins/mpay/pay/mpay.py, tools/plugins/mpay/pay/tests/test_invoice_check.py
=> feat: sanity check mpay invoice

lib/api/v2/routers/SwapRouter.ts, swagger-spec.json
I found 2 minor differences between the actual data types used and what has been documented.
=> Type fixes

docs/SUMMARY.md, docs/api-v2.md
=> docs: add emojis to swagger link

lib/db/Database.ts, lib/db/models/PendingLockupTransaction.ts, lib/db/repositories/PendingLockupTransactionRepository.ts, lib/notifications/NotificationProvider.ts, lib/rates/Errors.ts, lib/rates/LockupTransactionTracker.ts, lib/rates/RateProvider.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts, lib/swap/UtxoNursery.ts, test/integration/Utils.spec.ts, test/integration/rates/LockupTransactionTracker.spec.ts, test/unit/notifications/NotificationProvider.spec.ts, test/unit/rates/RateProvider.spec.ts, test/unit/swap/UtxoNursery.spec.ts
This PR adds a circuit breaker for 0-conf that disables it in case a lockup transaction cannot be found anymore
=> feat: 0-conf circuit breaker

docker/build.py, docker/regtest/startRegtest.sh, lib/VersionCheck.ts
Depends on https://github.com/lightningnetwork/lnd/issues/8571
=> chore: bump Bitcoin Core to v27.0

lib/api/Controller.ts, lib/api/Utils.ts, lib/api/v2/routers/SwapRouter.ts, test/unit/api/v2/routers/SwapRouter.spec.ts
Closes https://github.com/BoltzExchange/boltz-backend/issues/540
=> feat: allow specifying referral via URL query

lib/api/v2/routers/SwapRouter.ts, lib/service/Service.ts, swagger-spec.json, test/unit/service/Service.spec.ts
=> feat: return referral id in swap created response

docs/deployment.md, lib/Config.ts, lib/Utils.ts, lib/rates/RateProvider.ts, lib/rates/providers/RateProviderBase.ts, lib/rates/providers/RateProviderLegacy.ts, lib/rates/providers/RateProviderTaproot.ts, lib/service/Service.ts, lib/service/cooperative/DeferredClaimer.ts, lib/swap/SwapManager.ts, test/unit/Utils.spec.ts, test/unit/rates/RateProvider.spec.ts, test/unit/rates/providers/RateProviderBase.spec.ts, test/unit/rates/providers/RateProviderLegacy.spec.ts, test/unit/rates/providers/RateProviderTaproot.spec.ts, test/unit/service/Service.spec.ts
`cost of claim transaction * multiplier = minimial swap size`
=> feat: configurable minimal swap size multipliers

lib/service/Errors.ts, lib/service/cooperative/ChainSwapSigner.ts, lib/service/cooperative/EipSigner.ts, lib/service/cooperative/MusigSigner.ts, test/integration/service/cooperative/ChainSwapSigner.spec.ts, test/integration/service/cooperative/EipSigner.spec.ts, test/integration/service/cooperative/MusigSigner.spec.ts
=> feat: detailed cooperative refund rejection error

lib/api/v2/routers/SwapRouter.ts, lib/service/PaymentRequestUtils.ts, lib/service/Service.ts, lib/swap/Errors.ts, lib/swap/NodeFallback.ts, lib/swap/ReverseRoutingHints.ts, lib/swap/SwapManager.ts, swagger-spec.json, test/unit/api/v2/routers/SwapRouter.spec.ts, test/unit/service/PaymentRequestUtils.spec.ts, test/unit/service/Service.spec.ts, test/unit/swap/NodeFallback.spec.ts, test/unit/swap/ReverseRoutingHints.spec.ts
=> Custom invoice memo

lib/Config.ts, lib/Utils.ts, lib/consts/Types.ts, lib/db/models/ReverseSwap.ts, lib/db/models/Swap.ts, lib/db/repositories/ChainSwapRepository.ts, lib/service/EventHandler.ts, lib/swap/Errors.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts, lib/swap/UtxoNursery.ts, test/integration/db/models/Swap.spec.ts, test/integration/db/repositories/ChainSwapRepository.spec.ts, test/integration/swap/UtxoNursery.spec.ts, test/unit/Utils.spec.ts, test/unit/swap/UtxoNursery.spec.ts
=> feat: onchain overpayment protection

docs/0-conf.md, docs/SUMMARY.md, docs/api-v2.md, docs/claiming-swaps.md, docs/common-mistakes.md, docs/deployment.md
Replaces https://github.com/BoltzExchange/boltz-backend/pull/583
Based on https://github.com/BoltzExchange/boltz-backend/pull/602
=> Docs: Add "Common Mistakes" Page

docs/lifecycle.md
Preview: https://boltz.gitbook.io/api-boltz-backend-dev/lifecycle
=> docs: add swap status change info

lib/db/Database.ts, lib/db/models/TransactionLabel.ts, lib/db/repositories/TransactionLabelRepository.ts, lib/service/cooperative/CoopSignerBase.ts, lib/service/cooperative/DeferredClaimer.ts, lib/swap/SwapManager.ts, lib/swap/SwapNursery.ts, lib/wallet/ethereum/ContractHandler.ts, lib/wallet/ethereum/EthereumManager.ts, lib/wallet/providers/ERC20WalletProvider.ts, lib/wallet/providers/EtherWalletProvider.ts, test/integration/db/repositories/TransactionLabelRepository.spec.ts, test/integration/wallet/ethereum/ContractHandler.spec.ts, test/integration/wallet/ethereum/EthereumManager.spec.ts, test/integration/wallet/providers/ERC20WalletProvider.spec.ts, test/integration/wallet/providers/EtherWalletProvider.spec.ts, test/unit/swap/EthereumNursery.spec.ts
=> feat: EVM transaction labels

lib/api/v2/routers/SwapRouter.ts, lib/service/PaymentRequestUtils.ts, lib/service/Service.ts, swagger-spec.json, test/unit/service/PaymentRequestUtils.spec.ts
=> feat: chain swap creation with no amount

lib/service/BalanceCheck.ts, lib/service/Errors.ts, lib/service/Renegotiator.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, test/integration/service/BalanceCheck.spec.ts, test/integration/service/Renegotiator.spec.ts, test/unit/service/Service.spec.ts
=> feat: check balance before creating swap

lib/db/models/Swap.ts, lib/db/repositories/ChainSwapRepository.ts, test/integration/db/models/Swap.spec.ts, test/integration/db/repositories/ChainSwapRepository.spec.ts
=> fix: show lockup failure details only when status is lockup failed

lib/chain/MempoolSpace.ts, test/integration/chain/MempoolSpace.spec.ts, test/unit/chain/MempoolSpace.spec.ts
=> feat: mempool.space liveliness check

lib/db/repositories/SwapRepository.ts, test/integration/db/repositories/SwapRepository.spec.ts
=> fix: set failureReason to null when invoice is paid

lib/chain/ChainClient.ts, lib/chain/Rebroadcaster.ts, lib/db/Database.ts, lib/db/models/Rebroadcast.ts, lib/db/repositories/RebroadcastRepository.ts, test/integration/chain/ChainClient.spec.ts, test/unit/chain/Rebroadcaster.spec.ts
=> feat: transaction rebroadcaster

lib/api/v2/routers/SwapRouter.ts, lib/service/cooperative/ChainSwapSigner.ts, lib/service/cooperative/CoopSignerBase.ts, lib/service/cooperative/DeferredClaimer.ts, swagger-spec.json, test/integration/service/cooperative/DeferredClaimer.spec.ts
=> feat: coop claim Chain Swaps that send on EVM

docs/README.md, docs/SUMMARY.md, docs/libraries.md, docs/referral-program.md
Preview: https://boltz.gitbook.io/dev_boltz-api
=> docs: add library & referral section

docs/api-v2.md
=> docs: RSK swap code examples

.github/workflows/ci.yml
CI: 10 minutes -> 6 minutes 30 seconds
Rust build: 7 minutes -> 3 minutes 20 seconds
=> chore: add Rust build cache in CI

lib/Config.ts, lib/chain/ElementsWrapper.ts, lib/db/Migration.ts, lib/db/models/PendingEthereumTransaction.ts, lib/db/repositories/PendingEthereumTransactionRepository.ts, lib/wallet/ethereum/EthereumManager.ts, lib/wallet/ethereum/InjectedProvider.ts, lib/wallet/ethereum/SequentialSigner.ts, run-int.js, test/integration/db/repositories/PendingEthereumTransactionRepository.spec.ts, test/integration/wallet/ethereum/EthereumManager.spec.ts, test/integration/wallet/ethereum/InjectedProvider.spec.ts, test/integration/wallet/ethereum/SequentialSigner.spec.ts
=> feat: sequential EVM signer

lib/api/Controller.ts, lib/api/SwapInfos.ts, lib/api/v2/routers/ChainRouter.ts, lib/service/Service.ts, swagger-spec.json, test/unit/api/Controller.spec.ts, test/unit/api/SwapInfos.spec.ts, test/unit/api/v2/routers/ChainRouter.spec.ts, test/unit/service/Service.spec.ts
=> feat: confirmation status in transaction endpoint

lib/consts/Types.ts, lib/rates/RateProvider.ts, lib/rates/providers/RateProviderBase.ts, lib/rates/providers/RateProviderTaproot.ts, lib/service/PaymentRequestUtils.ts, lib/service/Service.ts, lib/service/cooperative/DeferredClaimer.ts, lib/swap/SwapManager.ts, test/integration/service/cooperative/DeferredClaimer.spec.ts, test/unit/rates/RateProvider.spec.ts, test/unit/rates/providers/RateProviderBase.spec.ts, test/unit/rates/providers/RateProviderTaproot.spec.ts, test/unit/service/PaymentRequestUtils.spec.ts, test/unit/service/Service.spec.ts
=> feat: batch-only submarine swaps

boltzr/src/api/bolt12.rs, boltzr/src/api/mod.rs, boltzr/src/db/helpers/offer.rs, boltzr/src/lightning/cln/hold.rs, boltzr/src/webhook/invoice_caller.rs, boltzr/src/webhook/types.rs, lib/api/v2/routers/LightningRouter.ts, swagger-spec.json
Closes #897
Closes #898
@dangeross please have a look too
=> BOLT12 followup

lib/Utils.ts, lib/api/v2/routers/SwapRouter.ts, lib/db/Migration.ts, lib/db/models/Swap.ts, lib/lightning/PendingPaymentTracker.ts, lib/service/Errors.ts, lib/service/Service.ts, lib/swap/SwapManager.ts, swagger-spec.json, test/unit/Utils.spec.ts, test/unit/api/v2/routers/SwapRouter.spec.ts, test/unit/lightning/PendingPaymentTracker.spec.ts
=> feat: submarine payment retry timeout

boltzr/src/api/ws/offer_subscriptions.rs, boltzr/src/api/ws/status.rs, boltzr/src/lightning/cln/hold.rs, docs/api-v2.md
Closes #912 
~Still needs docs~
=> feat: allow returning BOLT12 invoice errors

docs/pro.md
Preview: https://boltz.gitbook.io/docs-preview/pro
=> docs: add Boltz Client to Pro docs

.gitignore, boltzr/src/chain/chain_client.rs, boltzr/src/chain/elements_client.rs, docker/build.py, docker/regtest/data/core/config.conf, docker/regtest/data/elements/elements.conf, docker/regtest/scripts/configure.sh, docker/regtest/scripts/entrypoint.sh, docker/regtest/startRegtest.sh, docs/regtest.md, lib/Config.ts, test/integration/Nodes.ts
=> chore: switch bitcoind/elementsd to rpcauth
